using UnityEngine;
using System;
using System.Collections;

public class Knockback : MonoBehaviour
{
    public Action OnKnockbackStart;
    public Action OnKnockbackEnd;

    [SerializeField] private float _knockbackTime = .2f;
    

    private Vector3 _knockbackDirection;
    private float _knockbackForce;

    private Rigidbody2D _rigidBody;

    private void Awake()
    {
        _rigidBody = GetComponent<Rigidbody2D>();
    }
    private void OnEnable()
    {
        OnKnockbackStart += ApplyKnockBackForce;
        OnKnockbackEnd += StopKnockRoutine;
    }
    private void OnDisable()
    {
        OnKnockbackStart -= ApplyKnockBackForce;
        OnKnockbackEnd -= StopKnockRoutine;
    }
    public void GetKnockedBack(Vector3 hitDirection, float knockbackThrust)
    {
        _knockbackDirection = hitDirection;
        _knockbackForce = knockbackThrust;

        OnKnockbackStart?.Invoke();
    }
    private void ApplyKnockBackForce()
    {
        Vector3 difference = (transform.position - _knockbackDirection).normalized * _knockbackForce * _rigidBody.mass;
        _rigidBody.AddForce(difference, ForceMode2D.Impulse);
        StartCoroutine(KnockRoutine());
    }
    private IEnumerator KnockRoutine()
    {
        yield return new WaitForSeconds(_knockbackTime);
        OnKnockbackEnd?.Invoke();
    }
    private void StopKnockRoutine()
    {
        _rigidBody.linearVelocity = Vector2.zero;
    }

}
